name: Docker

on:
  workflow_dispatch: # allows to be run manually
  push:
    tags:
      - '*'
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build_and_push:
    name: Build (and push) Docker image
    if: github.repository_owner == 'LCAS'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lcas.lincoln.ac.uk/lcas/pretalx
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login LCAS
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          registry: lcas.lincoln.ac.uk
          username: ${{ secrets.LCAS_REGISTRY_PUSHER }}
          password: ${{ secrets.LCAS_REGISTRY_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
